language: php

php:
    - "5.2"
    - "5.3"
    - "5.4"
    - "5.5"

env:
    - WP_VERSION=master

matrix:
  include:
    - php: "5.4"
      env: WP_VERSION=3.8
    - php: "5.3"
      env: WP_VERSION=3.8

branches:
  except:
    - dev

before_script:
  - npm install -g grunt-cli
  - npm install

  
script: grunt test --verbose